FROM 998131032990.dkr.ecr.us-east-1.amazonaws.com/bazel:latest

# Re-copy sources from working tree
USER root
RUN apt-get update -y && apt-get install -y git libltdl-dev ruby ruby-dev
RUN gem install fpm
COPY . /vt/src/

# Build Vitess
RUN cd /vt/src/ && ./bazel_bootstrap.sh && bazel build :full_dist && cd /vt && tar -xvzf src/bazel-bin/full_dist.tar.gz

ENTRYPOINT []
